---
# handlers file for macterm

# at least on jan6 2019, the osx_defaults module does not allow to READ values (shame).
# alternatively run 'killall cfprefsd' command
- name: Read new iTerm profile after copying
  command: defaults read com.googlecode.iterm2
...
